### PR TITLE
style(cli): eslint prettier fix code formatting

### PR DESCRIPTION
**Pull request by Fecony**
## Description
When I worked on #1074, I noticed that I got more changes than I made because ESLint fixed the code style from the recently merged feature, but I decided to leave those changes for a separate PR.

PR to fix the code style for feature that was introduced in #651.
It seems that sometimes the ESLint action added in #658 doesn't work?? And because of this, the code is left with the wrong code style

## Changes
- Fixed code style

## Checks
- [x] Project Builds
- [x] Project passes tests and checks
- [ ] ~Updated documentation accordingly~

### CODE REVIEW

**Comment by gonzalogarciajaubert** [comment]
When script `scripts/check-all-the-things.sh` is run, it should fix them. Did you have any error run it? The script should run the following commands:

```
lerna run lint:fix --stream \
&& lerna run lint:check --stream
```

**Comment by Fecony** [comment]
Hey @gonzalogarciajaubert those changes are made by `scripts/check-all-the-things.sh`

**Review by gonzalogarciajaubert — APPROVED** [review]
LGTM

**Comment by gonzalogarciajaubert** [comment]
@Fecony, could you merge this branch into `Fecony:fix/1074_fix-stub-publishing`? This way we could run all the jobs only once

**Review by NickSeagull — APPROVED** [review]

**Pull request closed without merging**
