### PR TITLE
fix: getters not working when return type is a promise of an array of…

### PR DESCRIPTION
**Pull request by hendrik-depauw-lemon**
… objects

## Description
<Describe the purpose of this pull request>

## Checks
- [ ] Project Builds
- [ ] Project passes tests and checks
- [ ] Updated documentation accordingly

### CODE REVIEW

**Review by javiertoledo — APPROVED** [review]
LGTM

**Comment by hendrik-depauw-lemon** [comment]
Can we get this merged? 🙂

**Comment by davidverdu** [comment]
@hendrik-depauw-lemon you also need to add the changeset file. Please run `rush change` and commit the changeset file

**Comment by davidverdu** [comment]
Hi @hendrik-depauw-lemon it seems that `rush change`  generated a file that is not appealing to the GitHub action that checks it. Could you do these steps and regenerate the change file?
- ensure you have run in your local repository `git remote add boostercloud https://github.com/boostercloud/booster.git`, so that no warnings are displayed at executing `rush change`
- ensure you have rebased to the latest changes of the main repository

**Comment by hendrik-depauw-lemon** [comment]
I updated it, hopefully it's ok now

**Comment by davidverdu** [comment]
@hendrik-depauw-lemon merged!! Thank you for the contribution

**Pull request merged**
