### PR TITLE
fix(cli): h flag exit error (clone of PR #274)

### PR DESCRIPTION
**Pull request by alvaroloes**
This PR is a clone of PR #274 because integration tests could not be run on the original one. Refer to that PR for related information and discussion

### CODE REVIEW

**Comment by alvaroloes** [comment]
bot: integration

**Comment by alvaroloes** [comment]
bot: integration

**Comment by NickSeagull** [comment]
Integration tests are passing, but this doesn't change any "functional" part, right? Can this be merged @dotalo

**Comment by dotalo** [comment]
I thought that integration tests weren't passing, but yes this is only to solve the error when passing `-h` and does not involve functional changes ;)

**Comment by NickSeagull** [comment]
Awesome! Thanks a lot 😄 

@dotalo this has been the first contribution from someone external to our company and we would like to thank you with a special gift. Could you please contact with us so we can talk about the details like postal service? You can send an email to info@booster.cloud or via DM in Twitter.

**Pull request merged**
