### PR TITLE
Remove dependabot and update dependencies

### LINKED ISSUE #461: Remove "dependabot"
## Feature Request
Dependabot is doing more harm than good, as it updates direct dependencies but some transitive ones are not updates. This is causing some bugs that appear to be random because it depends on wether you have updated your yarn.lock file or not.

The idea is to remove it and make the update of dependencies manually when needed.

## Additional information
As part of this task, we should update dependencies to be in a fresh state with regard to dependencies.

### PR DESCRIPTION
**Pull request by alvaroloes**
## Description
Remove dependabot and update dependencies, especially those related to the `aws-infrastructure` (the CDK and SDK). They were really old and I needed to do changes in code to use the new way of deploying the app to AWS.

Also I fixed some integration tests. They seem to be more stable now.

This PR closes #461 

## Checks
- [x] Project Builds
- [ ] Project passes tests and checks
- ~[ ] Updated documentation accordingly~ Not needed

### CODE REVIEW

**Review by NickSeagull — APPROVED** [review]
I guess all these changes are related to the dependency bumps, so 🚢🇮🇹

**Comment by alvaroloes** [comment]
integration: all

**Comment by alvaroloes** [comment]
integration: all

**Review by juanjoman — APPROVED** [review]

**Comment by alvaroloes** [comment]
Integration tests are passing in the "actions tab" (checks are misguiding)

**Comment by javiertoledo** [comment]
Ooops, this change broke my refactor in #414 :trollface:

**Pull request merged**
