### PR TITLE
Add Commands onError hook

### PR DESCRIPTION
**Pull request by gonzalogarciajaubert**
## Description
Add Commands onError hook

## Checks
- [x] Project Builds
- [x] Project passes tests and checks
- [x] Updated documentation accordingly

# Note: Base branch: feature/add_local_after_filter

### CODE REVIEW

**Comment by javiertoledo** [comment]
I'm seeing commits from #1039 in this branch. Let's merge the other one and rebase this one before reviewing it.

**Comment by gonzalogarciajaubert** [comment]
You are right @javiertoledo , I just updated the base branch

**Review by rdiaz82 — APPROVED** [review]
LGTM but it seems that this branch is old and needs a rebase.

**Comment by gonzalogarciajaubert** [comment]
@rdiaz82 @javiertoledo take a look to this one https://github.com/boostercloud/booster/pull/1052. Closing this one as there are wrong commits

**Pull request closed without merging**
