### PR TITLE
Added sourceMap: true to the template tsconfig.json for debugging #1466

### PR DESCRIPTION
**Pull request by yashp4858**
## Description
<Describe the purpose of this pull request>
Added sourceMap: true to the template tsconfig.json for debugging #1466
## Checks
- [ ] Project Builds
- [ ] Project passes tests and checks
- [ ] Updated documentation accordingly

### CODE REVIEW

**Comment by yashp4858** [comment]
@NickSeagull @javiertoledo pls have look at this PR.

**Review by javiertoledo — APPROVED** [review]
LGTM

**Comment by javiertoledo** [comment]
Oh, it seems that this PR duplicates #1467

**Comment by yashp4858** [comment]
@javiertoledo okay so should I take this pr back. I have not it intentionally

**Comment by javiertoledo** [comment]
No problem @yashp4858. I'll close this one because #1467 was submitted earlier, but your contribution is equally appreciated. Thanks for making the effort!

**Comment by javiertoledo** [comment]
No problem @yashp4858. I'll close this one because #1467 was submitted earlier, but your contribution is equally appreciated. Thanks for making the effort!

**Pull request closed without merging**
