### PR TITLE
Fix node 16 bug at deployment

### LINKED ISSUE #823: Deployment fails on node 16
# Bug Report
Executing the Getting Started instructions (http://docs.booster.cloud/#/chapters/02_getting-started) from Booster Cloud, deployment fails when using node 16.
First it fails with the error message:
```
 boost deploy -e production
(node:63) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
    Error: ENOENT: no such file or directory, stat '.deploy'
    Code: ENOENT
```
After creating the .deploy directory manually, it fails with the following error:
```
3:19:37 PM | CREATE_FAILED        | AWS::Lambda::Function                  | eventsmain7D354D31
Resource handler returned message: "Uploaded file must be a non-empty zip (Service: Lambda, Status Code: 400, Request ID: b9baae6f-b67a-4d27-8f70-2b88a571fbba, Extended Request
[··················································] (4/36)
```

## Expected behavior
Should successfully deploy

## Possible Solution

N/A

### Environment
- Booster version: @boostercloud/cli/0.16.0 linux-x64 node-v16.1.0
node  v16.1.0
npm 7.11.2
- OS: Docker image node:16

### PR DESCRIPTION
**Pull request by adriangmweb**
## Description
There is an issue when deploying on node v16 or later where CloudFormation fails because the Lambda zip files are empty. After some investigation seems that there is an [issue with the `aws-cdk` ](https://github.com/aws/aws-cdk/issues/12536)version that we were using.

Also, we were using the `rmDir` function from the node `fs` package which [has been deprecated on node v16](https://github.com/nodejs/node/pull/37302).

Closes #823 

## Changes
- Upgrade `aws-cdk` and `aws-sdk` versions to the latest stable, compatible and reliable without breaking changes versions that fix that error.
- Use `rm({recursive: true})` instead of the deprecated `rmDir` function form the node `fs` package.
- Updated all node dependencies to use at least `v14.14`

## Checks
- [x] Project Builds
- [x] Project passes tests and checks
- [x] Updated documentation accordingly
 
## Additional information
These changes have been tested on node v14, node v15, and node v16.

### CODE REVIEW

**Review by juanjoman — APPROVED** [review]
LGTM! We should also update these versions for all rockets when possible

**Review by alvaroloes — APPROVED** [review]
Thanks!

**Review by alvaroloes — COMMENTED** [review]
Just remember to check the unit tests (they are failing) and integration tests

**Comment by adriangmweb** [comment]
> Just remember to check the unit tests (they are failing) and integration tests

Working on it 🚀

**Pull request merged**
