### PR TITLE
[548] add booster config to rocket mount

### PR DESCRIPTION
**Pull request by rdiaz82**
## Description
Added booster configuration to mount method of the public rocket interface

## Changes
Small changes in provider-aws-infrastructure

## Checks
- [X] Project Builds
- [X] Project passes tests and checks
- [X] Updated documentation accordingly

### CODE REVIEW

**Review by NickSeagull — APPROVED** [review]
LGTM!

**Review by juanjoman — APPROVED** [review]
Thankss!! 🙏

**Comment by NickSeagull** [comment]
Locking to pass integration tests

**Review by javiertoledo — APPROVED** [review]
LGTM, but make sure that you add this extra parameter to the tests!

**Review by alvaroloes — APPROVED** [review]
This is a key change! :shipit:

**Comment by alvaroloes** [comment]
@rdiaz82 Rebase and the integration tests should run OK

**Comment by rdiaz82** [comment]
this PR has problems with rebasing I have created a new PR

**Pull request closed without merging**
