### PR TITLE
[WIP] feat(cli): ask to override files

### PR DESCRIPTION
**Pull request by Fecony**
## Description
Check if project folder or resource already exist before generating new file. It will ask user if he wants to override existing file and continue or stop generating. If user agrees to override it file/project folder is removed. If declines then it will throw error for user to use different resource name. (See Images below) 

Closes https://github.com/boostercloud/booster/issues/305

## Changes
- Checks if project or file already exist.
- export `projectDir()`
- Adds `checkProjectAlreadyExists()` to check if project already exists in current directory.
- Adds `checkResourceExists()` to check if resource already exists.
- Unit tests for `checkProjectAlreadyExists()` and `checkResourceExists()` methods
- Adds `confirmPrompt()` which is used by `checkProjectAlreadyExists()` and `checkResourceExists()` to reuse same code
- Adds `filePath` function which was used in single method, to get path where resource should be generated. Is used for generation and to check if resource exists
- Adds `FileDir` type for `filePath` method to pick only required params `'placementDir' | 'name' | 'extension'`
- Adds `getResourceType()` to get resource name from path.

## Checks
- [x] Project Builds
- [x] Project passes tests and checks
- [ ] Updated documentation accordingly
 

Screenshot 2020-10-21 at 23 12 36
Screenshot 2020-10-21 at 23 12 40

### CODE REVIEW

**Comment by javiertoledo** [comment]
FYI, #476 changes significantly how CLI integration tests work, so I'd avoid changing/implementing integration tests in this PR until #476 is merged. If we review/approve this faster, we can merge this PR and implement the tests in a separate issue or keep this PR open until the other is merged.

**Comment by javiertoledo** [comment]
Hey @Fecony, just tool a deeper look at your code and I have some ideas/suggestions:

1. Checking the existence of the files in the commands could end up being a bit fragile for future changes because someone could forget about it when creating new commands or delete the check accidentally, and I like the idea of making these checks the default for code generators. I think I'd do it directly in the `generate` function in [`packages/cli/src/services/generator.ts`](https://github.com/boostercloud/booster/blob/master/packages/cli/src/services/generator.ts).

2. There's a `Prompter` class in `user-prompt.ts` with a couple of methods using `inquirer`. It would be nice to put the `confirmPrompt` function in there to keep consistency.

3. I liked the idea of having this `project-checker` service to encapsulate this functionality, and as it's designed in this nice functional fashion, I think you should be able to use it from the `generate` function or any other place where you decide to put the checks.

What do you think? Maybe there's a better place to put the checks, but I'd definitely avoid doing it explicitly in the commands.

**Comment by Fecony** [comment]
Hey, @javiertoledo. 

1. I have moved promt to Prompter class. 
2. Moved resource existence check to `generate` method

Now it will check if resource exists and print info message about it before printing prompt or generation text. 
Screenshot 2020-10-28 at 21 36 45

**Review by javiertoledo — COMMENTED** [review]
Good work! The code is looking great, the only thing I'm missing is unit tests checking that the prompt is printed when a file exists and what happens when the user chooses to override or cancel the action. Once we merge #476, we could come back to this and implement a couple of integration tests too. Thanks a lot!

**Comment by Fecony** [comment]
@javiertoledo Yep, #476 with it `createSandboxProject` is something I would like to use in unit tests too, I tried to write unit tests for this PR, but faced problems with creating / clearing test project files. Will wait for #476 . Let me know when I can continue working on this PR!

**Comment by javiertoledo** [comment]
@Fecony #476 was merged, so you can rebase and use the `createSandboxProject` helper function now :-)

**Comment by Fecony** [comment]
@javiertoledo  Hey! I started to work with unit tests and I am confused with `createSandboxProject` method...

The problem is, it copies `src` folder of `packages/cli` (the `origin` folder where test is running) folder and not integrations tests `src/` folder that has test files(?) 

I am not sure if it was planned to use `createSandboxProject` method only in integration tests and that means I am doing some :poop: with it in unit tests. But I don't know 😄


Let me know if I am wrong and should not use it in unit tests. Also if it is the case maybe you can tell me what exactly I should test in unit tests? 🤔

**Comment by javiertoledo** [comment]
@Fecony yes, the `createSandboxProject` package is designed to run in the integration tests only. This is because in unit tests we're mocking the interfaces and focusing on checking that all methods are calling to the right APIs with the right parameters, so no real files should be checked or created. This makes unit tests faster and more reliable (this is good because we run them often during dev). Integration tests do the real stuff; they're slower and run primarily in the CI/CD process. In the integration tests package, [you can find a couple of cli integration tests](https://github.com/boostercloud/booster/tree/master/packages/framework-integration-tests/integration/cli). Those tests are creating this sandbox folder where they can safely mess with actual files. Once the test is done, we remove the sandbox folder.

**Review by NickSeagull — APPROVED** [review]
Lovely, thanks for this! The only thing I'm missing is what @javiertoledo pointed :D

**Review by alvaroloes — APPROVED** [review]
@Fecony Love the PR! Thanks a lot for this. Once you have the unit test in place (those Javi mentioned) and checked that the documentation is updated, this PR is good to go. Pre-approving!

**Comment by davidverdu** [comment]
Hi @Fecony great work!! I think we have almost ready to merge. We want to move this PR to improve the framework. We also need to rebase with `main` before merging. Do you need help? Please join our [Discord](https://discord.gg/k7b4B8CDtT) community to solve doubts. Thank you!

**Comment by Fecony** [comment]
@davidverdu, @javiertoledo, uff, I tried to write tests last time in november... 
After that I switched to my job. and quite forgot about booster.. I am reading about new things happening in it. But I don't know much what has changed.

I may try to write tests on this weekend. If you didn't decide to take take care of this PR 😄

**Comment by Fecony** [comment]
@davidverdu, @javiertoledo rebased & added unit tests!
I hope now it can be merged. If there is anything this PR is missing, let me know 😄

**Comment by davidverdu** [comment]
> @davidverdu, @javiertoledo rebased & added unit tests!
> I hope now it can be merged. If there is anything this PR is missing, let me know 😄

Hi @Fecony there is a unit test which is failing. Could you review it? If you need help let us know. To run the unit tests just type `lerna run test --stream`

**Comment by Fecony** [comment]
Hey, @davidverdu fixed unit tests 📦

**Comment by davidverdu** [comment]
> Hey, @davidverdu fixed unit tests 📦

Thank you so much @Fecony . However, the integration tests, which are run with `lerna run integration --stream` are broken because 2 tests are trying to create files that already exist and get blocked with the prompt. To fix this is easy:

In `packages/framework-integration-tests/integration/cli/cli.event.integration.ts`, go to the case `without fields` => `should create new event` and add the line `removeFiles([FILE_CART_CHANGED_EVENT])` before executing the command.

A similar change is needed in the file `packages/framework-integration-tests/integration/cli/cli.readmodel.integration.ts`. Remember to add the dependency at the top of each file.

Another thing you need to do is to rebase again with main, since we have added new lines of code.

Integration tests must work properly before accepting the PR. Thank you, you are almost ready for merge!

**Review by davidverdu — CHANGES_REQUESTED** [review]
Integration tests need to be fixed. I left a commend with instructions to solve the problem

**Review by davidverdu — APPROVED** [review]
Integration tests have been fixed and the pass locally. Let's merge to `contrib` branch first, in order to run integration tests in GitHub first, with the AWS credentials to run the tests

**Pull request merged**
