### PR TITLE
chore(cicd): Try caching build and dependencies

### PR DESCRIPTION
**Pull request by NickSeagull**
## Description

We spend like 10 minutes for installing and building for each job in the CICD, this PR mitigates that by caching.

## Changes

Caches the Rush project before building

## Checks
- [ ] Project Builds
- [ ] Project passes tests and checks
- [ ] Updated documentation accordingly

### CODE REVIEW

**Review by BorjaZarco — APPROVED** [review]
LGTM! 👍

**Review by javiertoledo — APPROVED** [review]
🚢 🇮🇹 ❗

**Review by adrian-lorenzo — APPROVED** [review]

**Pull request merged**
