### PR TITLE
Fecony/fix/620 fix resource name generation

### PR DESCRIPTION
**Pull request by davidverdu**
## Description
PR to add a contribution from the community https://github.com/boostercloud/booster/pull/660

## Changes
- Add method resourceNameToClassName() to generate class name from passed resource name.
- Add few tests for resourceNameToClassName() and classNameToFileName() functions in filenames.ts
- Adjust generator test.
- Formatting in generator test was fixed.

## Checks
- [x ] Project Builds
- [x ] Project passes tests and checks
- [x ] Updated documentation accordingly

### CODE REVIEW

**Review by juanjoman — APPROVED** [review]

**Review by Moneyba — APPROVED** [review]

**Review by alvaroloes — APPROVED** [review]
It seems CLI integration tests are not passing

**Review by davidverdu — COMMENTED** [review]
Hi @Fecony , The CLI integration tests are not passing due to a bug with plural names. 
(1) Please add in your unit tests examples with plurals `testResources`, `TestResourceNames` and more tricky ones (English language has different plural with s and es)
(2) Please ensure that `Lerna run integration/cli --stream` executes without errors

**Comment by NickSeagull** [comment]
@boostercloud/booster-core remember to unlock conversation right after locking it ;)

**Comment by Fecony** [comment]
@davidverdu Updated code to throw error in #805

**Pull request merged**
