### PR TITLE
Add a section for installing the Booster CLI

### PR DESCRIPTION
**Pull request by itrion**
## Description
In the rewriting of the docs we will be opening several PRs, one per section, so we end up with the documentation in a single markdown file.

## Changes
Add a section for Installing the Booster CLI so a user can later follow the 10 minutes tutorial

## Checks
- [ ] Project Builds
- [ ] Project passes tests and checks
- [ ] Updated documentation accordingly at [the docs repo](https://github.com/boostercloud/docs)
- [ ] Added a link pointing to the documentation PR in this PR

### CODE REVIEW

**Comment by tainguyenbui** [comment]
bot: integration

**Comment by tainguyenbui** [comment]
@itrion when all tests pass, should we get this merged?

**Comment by itrion** [comment]
bot: integration

**Comment by alvaroloes** [comment]
Regarding tests: I'm still trying to fix the checks: They didn't pass because they are not run if the only files you changed are `*.md`. The problem is that if they are not run, the checks are not updated.

**Pull request merged**
